steps:
  # build and host the backend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/backend:$COMMIT_SHA',
        '-f',
        './backend/Dockerfile',
        './backend',
      ]


  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend:$COMMIT_SHA']


  # Deploy the user-service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        '${_SERVICE_NAME}',
        '--image',
        'gcr.io/$PROJECT_ID/backend:$COMMIT_SHA',
        '--region',
        '${_REGION}',
        '--port',
        '${_PORT}',
        '--allow-unauthenticated',
      ]

options:
  logging: CLOUD_LOGGING_ONLY
# asia-southeast1

images:
- 'gcr.io/$PROJECT_ID/backend:$COMMIT_SHA'